/*
 * This file is generated by jOOQ.
 */
package com.jakub_lewandowski.gwent_backend.jooq;


import com.jakub_lewandowski.gwent_backend.jooq.tables.Players;
import com.jakub_lewandowski.gwent_backend.jooq.tables.records.PlayersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PlayersRecord> PLAYERS_PKEY = Internal.createUniqueKey(Players.PLAYERS, DSL.name("players_pkey"), new TableField[] { Players.PLAYERS.ID }, true);
}
