/*
 * This file is generated by jOOQ.
 */
package com.jakub_lewandowski.gwent_backend.jooq;


import com.jakub_lewandowski.gwent_backend.jooq.tables.Players;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.players</code>.
     */
    public static final Players PLAYERS = Players.PLAYERS;
}
